def render_report(title: str, sections: list[str]) -> str:
    body = "\n\n".join(sections)
    return f"# {title}\n\n{body}"


def render_business_report(
    title: str,
    data_sources: list[str] | None = None,
    findings: list[str] | None = None,
    analysis: str | None = None,
    knowledge_basis: list[str] | None = None,
    recommendations: list[str] | None = None,
) -> str:
    sections = [
        f"## Data Sources\n{_bullets(data_sources)}",
        f"## Key Findings\n{_bullets(findings)}",
        f"## Analysis\n{analysis or 'No additional analysis was provided.'}",
        f"## Knowledge Basis\n{_bullets(knowledge_basis)}",
        f"## Recommendations\n{_bullets(recommendations)}",
        "## Generated At\nGenerated by Enterprise Multi-Tool Agent Platform.",
    ]
    return render_report(title, sections)


def _bullets(items: list[str] | None) -> str:
    if not items:
        return "- Not provided."
    return "\n".join(f"- {item}" for item in items)
